# Base image Node.js
FROM node:18-alpine

# Direktori kerja di dalam container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package.json* ./

# Install dependencies
RUN npm cache clean --force && npm install

# Copy aplication source code
COPY . .

# Expose port aplikasi
EXPOSE 3000

# Command untuk menjalankan aplikasi
CMD [ "npm", "start" ]